export const USER_BOOKING_REQUEST = 'USER_BOOKING_REQUEST'
export const USER_BOOKING_SUCCESS = 'USER_BOOKING_SUCCESS'
export const USER_BOOKING_FAIL = 'USER_BOOKING_FAIL'

export const LIST_MY_BOOKING_REQUEST = 'LIST_MY_BOOKING_REQUEST'
export const LIST_MY_BOOKING_SUCCESS = 'LIST_MY_BOOKING_SUCCESS'
export const LIST_MY_BOOKING_FAIL = 'LIST_MY_BOOKING_FAIL'


export const USERS_BOOKING_REQUEST = 'USERS_BOOKING_REQUEST'
export const USERS_BOOKING_SUCCESS = 'USERS_BOOKING_SUCCESS'
export const USERS_BOOKING_FAIL = 'USERS_BOOKING_FAIL'
